### PR TITLE
Raise our own errors instead of Dalli errors

### LINKED ISSUE #8: Raise `Twingly::UrlCache::ServerError` instead of letting Dalli errors pass
It is quite common that we have short server issues when using Memcached on Heroku. Depending on the application it might make sense to pause/raise or to just ignore. I think it would look better if we could expose an exception from this library instead of the Dalli errors.

Example  (from Remora):

```
Dalli::RingError: No server available
  from dalli/ring.rb:45:in `server_for_key'
  from dalli/client.rb:361:in `perform'
  from dalli/client.rb:58:in `get'
  from twingly/url_cache.rb:27:in `block in cached?'
  from retryable.rb:67:in `retryable'
...
```

### PR DESCRIPTION
**Pull request by roback**
#8 has been open for quite a while, thought I give it a try.

This works, but the tests uses "allow_any_instance_of" which isn't that nice. Any improvement ideas welcome :)

close #8

### Todo

- [x] Add specs for retries, there were none before ([f18173f](/twingly/twingly-url_cache/pull/9/commits/f18173fe1b7074da1e1d6b5a3c8e71640018ca7d))

### CODE REVIEW

File: lib/twingly/url_cache.rb [hunk 1]
```diff
@@ -5,26 +5,38 @@
...
       @ttl = ttl
     end
 
     def cache!(url)
       key = key_for(url)
-      Retryable.retryable(tries: 3, on: Dalli::RingError) do
-        !!@cache.set(key, CACHE_VALUE, ttl, raw: true)
+
+      with_memcached_exception_handling do
+        Retryable.retryable(tries: 3, on: Dalli::RingError) do
```
Comment (walro) [inline lib/twingly/url_cache.rb]: I think we should use `retryable`'s block rather than introducing yet another level of blocks. It seems like the exception is yieled to the block, see for instance: https://github.com/nfedyashev/retryable#matching-error-messages

Comment (walro) [reply lib/twingly/url_cache.rb]: Also, looking at https://github.com/petergoldstein/dalli/blob/b50bb8245758a722f9525d44f05136cd3a0dac43/lib/dalli.rb#L12-L23 there might be more things "retryable" (`NetworkError` specifically)

Comment (roback) [reply lib/twingly/url_cache.rb]: > I think we should use `retryable`'s block rather than introducing yet another level of blocks. It seems like the exception is yieled to the block, see for instance: https://github.com/nfedyashev/retryable#matching-error-messages

Smart, I'll take a look at that.

> Also, looking at https://github.com/petergoldstein/dalli/blob/b50bb8245758a722f9525d44f05136cd3a0dac43/lib/dalli.rb#L12-L23 there might be more things "retryable" (`NetworkError` specifically)

That I noticed, but we have never seen the NetworkError before (couldn't find any issues regarding that anyway), so I just ignored it.

Comment (roback) [reply lib/twingly/url_cache.rb]: Some improvements in 9a1097fd4a6837fcdf97658df46c5ff941399563

File: lib/twingly/url_cache.rb [hunk 2]
```diff
@@ -47,5 +55,13 @@ def options
     def servers
       ENV.fetch("MEMCACHIER_SERVERS") { "localhost" }.split(",")
     end
+
+    def with_memcached_exception_handling(&block)
```
Comment (walro) [inline lib/twingly/url_cache.rb]: I feel the method name hides the fact that retries are part of the mix. Also, the method seems to be doing two separate things, perhaps revise into a two step rocket?

Comment (roback) [reply lib/twingly/url_cache.rb]: Isn't the retries is part of the exception handling? :)

Moving the retries to a separate method might make things a little more clear though.

Comment (walro) [reply lib/twingly/url_cache.rb]: IMHO, the two separate things that are going on here are:

* Retrying
* Converting exception types

Also, I withhold that looking at the method name you can't really figure out that the method will retry. One could pass a retry parameter to make that part more clear though.

Comment (roback) [reply lib/twingly/url_cache.rb]: Changed the name of the method in b8f06a3 and also made a separate method of the "retry" part to make it a bit easier to understand what happens.

File: lib/twingly/url_cache.rb [hunk 3]
```diff
@@ -5,25 +5,33 @@
 
 module Twingly
   class UrlCache
+    class Error < StandardError; end
+    class ServerError < Error; end
```
Comment (walro) [inline lib/twingly/url_cache.rb]: perhaps too much ceremony to move these to an `errors.rb` file? 😄

Comment (roback) [reply lib/twingly/url_cache.rb]: The gem only has one file (+ a `version.rb` file) and I didn't think it was worth introducing another one for just two lines :)

Comment (walro) [reply lib/twingly/url_cache.rb]: Sure :)

**Comment by walro** [comment]
WDYT of this approach:

```diff
diff --git a/lib/twingly/url_cache.rb b/lib/twingly/url_cache.rb
index d2b34e6..cd7f34f 100644
--- a/lib/twingly/url_cache.rb
+++ b/lib/twingly/url_cache.rb
@@ -14,32 +14,32 @@ module Twingly
 
     def initialize(ttl: 0)
       @cache = retry_transient_exceptions do
-        handle_memcached_exceptions do
-          Dalli::Client.new(servers, options)
-        end
+        Dalli::Client.new(servers, options)
       end
 
       @ttl = ttl
+    rescue Dalli::DalliError => error
+      remap_error(error)
     end
 
     def cache!(url)
       key = key_for(url)
 
       retry_transient_exceptions do
-        handle_memcached_exceptions do
-          !!@cache.set(key, CACHE_VALUE, ttl, raw: true)
-        end
+        !!@cache.set(key, CACHE_VALUE, ttl, raw: true)
       end
+    rescue Dalli::DalliError => error
+      remap_error(error)
     end
 
     def cached?(url)
       key = key_for(url)
 
       retry_transient_exceptions do
-        handle_memcached_exceptions do
-          @cache.get(key, raw: true) == CACHE_VALUE
-        end
+        @cache.get(key, raw: true) == CACHE_VALUE
       end
+    rescue Dalli::DalliError => error
+      remap_error(error)
     end
 
     private
@@ -62,16 +62,17 @@ module Twingly
       ENV.fetch("MEMCACHIER_SERVERS") { "localhost" }.split(",")
     end
 
-    def handle_memcached_exceptions
-      yield
-    rescue Dalli::RingError => error
-      raise ServerError, error.message
-    rescue Dalli::DalliError => error
-      raise Error, error.message
-    end
-
     def retry_transient_exceptions(&block)
       Retryable.retryable(tries: 3, on: ServerError, &block)
     end
+
+    def remap_error(error)
+      case error
+      when Dalli::RingError
+        raise ServerError, error.message
+      else
+        raise Error, error.message
+      end
+    end
   end
 end
```

**Comment by roback** [comment]
Now this part won't work since we "remap" the errors after we call "retry":

```ruby
     def retry_transient_exceptions(&block)
       Retryable.retryable(tries: 3, on: ServerError, &block)
     end
```

I kinda like having the rescue in one place. If we needed to add another rescue (if another exception than `Dalli::DalliError` gets raised, which may not be that likely :)) we would have to update in 4 different places. In the `remap_error` method and all places where it's called from.

**Comment by walro** [comment]
Aha, I think the specs needs to be touched up then, cause they still passed 😄

**Comment by roback** [comment]
> Aha, I think the specs needs to be touched up then, cause they still passed 😄

Hehe, oops 😄

There are no specs for retries at all, which would explain this. I'll try to add some while I'm at it.

**Comment by walro** [comment]
> I kinda like having the rescue in one place. If we needed to add another rescue (if another exception than `Dalli::DalliError` gets raised, which may not be that likely :)) we would have to update in 4 different places. In the `remap_error` method and all places where it's called from.

Could introduce a variable holding the exceptions, should take care of most repetition. The reason to why I proposed the change was in an attempt to improve clarity. More specifically, what does handle in `handle_memcached_exceptions` mean? If we could find another method name, it might work out well though.

**Comment by roback** [comment]
Something like `convert_memcached_exceptions_to_custom_exceptions` I think works. There may be a better word than "custom" though.

**Comment by walro** [comment]
hmm, perhaps 

```ruby
with_exception_class_conversion do
...
```

?

**Comment by roback** [comment]
Yes, that could work

**Comment by walro** [comment]
Great! I'll try to take a look at the specs tomorrow, haven't done so yet 😄

**Comment by roback** [comment]
> Great! I'll try to take a look at the specs tomorrow, haven't done so yet 😄

😨

File: lib/twingly/url_cache.rb [hunk 4]
```diff
@@ -5,26 +5,40 @@
...
+
     attr_reader :ttl
 
     CACHE_VALUE = ""
 
     def initialize(ttl: 0)
```
Comment (walro) [inline lib/twingly/url_cache.rb]: I think we could have better specs if we do this:

```ruby
 def initialize(ttl: 0, cache: default_cache)
  @cache = cache
  ...
end

def default_cache
  Dalli::Client.new(servers, options)
end
```

Hopefully we can kill of many `any_instance_of` as we can inject our own test double where applicable.

Comment (roback) [reply lib/twingly/url_cache.rb]: Doing it that way would get rid of all `any_instance_of` I think. I'll give it a try.

Comment (roback) [reply lib/twingly/url_cache.rb]: cc06220

File: spec/lib/url_cache_spec.rb [hunk 5]
```diff
@@ -24,44 +24,93 @@
...
+      before do
+        allow(dalli_client)
+          .to receive(dalli_method_name)
+          .and_raise(dalli_error)
+      end
+
+      context "when a Dalli::RingError is raised" do
+        let(:dalli_error_class) { Dalli::RingError }
+
+        it "should retry a few times" do
```
Comment (walro) [inline spec/lib/url_cache_spec.rb]: refrain from using "should" also a few is pretty loose, I'd suggest "it retries #{expected_retries} times" and we defined that variable.

Comment (walro) [reply spec/lib/url_cache_spec.rb]: (same with all "shoulds")

Comment (roback) [reply spec/lib/url_cache_spec.rb]: :+1:

Comment (roback) [reply spec/lib/url_cache_spec.rb]: Changed it in 4d665e0

All other specs (specs without an explicit description) outputs `should`, that's probably why I went with that word :)

```
Twingly::UrlCache
  should respond to #ttl
  should respond to #cache!
  should respond to #cached?
  #ttl
    ...
```

Comment (walro) [reply spec/lib/url_cache_spec.rb]: yeah, I wish RSpec would change that :)

File: spec/lib/url_cache_spec.rb [hunk 6]
```diff
@@ -24,44 +24,93 @@
...
+      before do
+        allow(dalli_client)
+          .to receive(dalli_method_name)
+          .and_raise(dalli_error)
+      end
+
+      context "when a Dalli::RingError is raised" do
+        let(:dalli_error_class) { Dalli::RingError }
+
+        it "retries a few times" do
```
Comment (walro) [inline spec/lib/url_cache_spec.rb]: not sure you saw my comment in https://github.com/twingly/twingly-url_cache/pull/9#discussion_r261588141 concerning this, so I'll repeat it.

I think we should change "few" to something more "spec-y". It could state "it retries three times" instead. Or even make a variable that we make use of in text and in assertion.

Comment (roback) [reply spec/lib/url_cache_spec.rb]: I must have missed that part, sorry.

> Or even make a variable that we make use of in text and in assertion.

That sounds good. The point of writing "a few" was just because I didn't want to hardcode a "3" in the text that could get out of date easily.

Comment (roback) [reply spec/lib/url_cache_spec.rb]: > The point of writing "a few" was just because I didn't want to hardcode a "3" in the text that could get out of date easily.

Although I don't think we will change this very often :)

Comment (roback) [reply spec/lib/url_cache_spec.rb]: f259f7a

**Comment by roback** [comment]
I guess this is a breaking change, so we need to bump the version to 2.0 when releasing this.

**Comment by walro** [comment]
> I guess this is a breaking change, so we need to bump the version to 2.0 when releasing this.

Hmm, not necessarily. Wait a minute, I will try dig something up from my memory.

**Comment by walro** [comment]
> Hmm, not necessarily. Wait a minute, I will try dig something up from my memory.

I was likely thinking of https://github.com/twingly/twingly-url/blob/bf19d12cdc176d60d76640dd5d3bb5e43f61543f/lib/twingly/url.rb#L49-L52 (thx @roback for the refresher). But I guess we don't have to go to that extent here.

**Comment by roback** [comment]
> I was likely thinking of https://github.com/twingly/twingly-url/blob/bf19d12cdc176d60d76640dd5d3bb5e43f61543f/lib/twingly/url.rb#L49-L52 (thx @roback for the refresher). But I guess we don't have to go to that extent here.

Yes, I'll just release 2.0 to keep things simple.
